import turtle
durachok = turtle.Turtle()
durachok.hideturtle()
def Dima():
    durachok.penup()
    durachok.goto(-200,200)
    durachok.pendown()
    durachok.begin_fill()
    durachok.forward(300)
    durachok.right(45)
    durachok.forward(150)
    durachok.right(90)
    durachok.forward(150)
    durachok.right(45)
    durachok.forward(300)
    durachok.right(90)
    durachok.forward(213)
    durachok.fillcolor("green")
    durachok.end_fill()
Dima()
turtle.exitonclick()import turtle
durachok = turtle.Turtle()
durachok.hideturtle()
print("idi v podval :)")
turtle.exitonclick()