import turtle
mainTurtle = turtle.Turtle()
def Dima(x,y):
    mainTurtle.penup()
    mainTurtle.goto(x,y)
    mainTurtle.pendown()
    mainTurtle.begin_fill()
    mainTurtle.forward(300)
    mainTurtle.right(45)
    mainTurtle.forward(150)
    mainTurtle.right(90)
    mainTurtle.forward(150)
    mainTurtle.right(45)
    mainTurtle.forward(300)
    mainTurtle.right(90)
    mainTurtle.forward(213)
    mainTurtle.fillcolor("green")
    mainTurtle.end_fill()
#Dima(-200,200)
mainTurtle.hideturtle()
turtle.exitonclick()